services:
  app:
    container_name: pki-2fa
    build: .
    ports:
      - "8000:8000"
    volumes:
      - seed-data:/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

volumes:
  seed-data:
